name: MobLimiter
version: ${project.version}
description: Control the mob population
authors: ["Travis Watkins", "redwall_hp"]

main: nu.nerd.moblimiter.MobLimiter

commands:
    moblimiter:
        description: Gives information about MobLimiter
