name: MobLimiter
version: ${project.version}
description: Control the mob population
authors: ["Travis Watkins", "redwall_hp"]

main: nu.nerd.moblimiter.MobLimiter

permissions:
  moblimiter.*:
    description: Access all commands
    default: op
    children:
      moblimiter.reload: true
      moblimiter.count: true
      moblimiter.limits: true
      moblimiter.check: true
  moblimiter.reload:
    description: Access to reload command
    default: op
  moblimiter.count:
    description: Access to count command
    default: op
  moblimiter.limits:
    description: Access to limits command
    default: op
  moblimiter.check:
    description: Access to check command
    default: op

commands:
  moblimiter:
    description: Gives information about MobLimiter
